"""Generate config files from DB for each project."""
import os
import logging
import yaml
import json
from pathlib import Path

from config import settings

logger = logging.getLogger(__name__)


def write_feature_gates(items: list) -> str:
    """Write feature_gates.yaml from DB items. Returns the file path."""
    gates = {}
    for item in items:
        # Try JSON parse for structured values (enabled + tier)
        try:
            data = json.loads(item.value)
            if isinstance(data, dict):
                gates[item.key] = {
                    "enabled": data.get("enabled", False),
                    "tier": data.get("tier", 1),
                    "description": data.get("description", item.description),
                }
            elif isinstance(data, bool):
                gates[item.key] = {
                    "enabled": data,
                    "tier": 1,
                    "description": item.description,
                }
            else:
                raise json.JSONDecodeError("not a gate object", item.value, 0)
        except (json.JSONDecodeError, TypeError):
            gates[item.key] = {
                "enabled": item.value.lower() in ("true", "1", "yes"),
                "tier": 1,
                "description": item.description,
            }

    # Load tier info from config items if present
    # (tier info stored as separate config items like "feature_flag_tier.xxx")

    output = {}
    output["version"] = "1"
    output["gates"] = gates
    output["_generated_by"] = "ops-center"
    output["_generated_at"] = __import__("datetime").datetime.utcnow().isoformat()

    path = settings.orchestrator_feature_gates_path
    os.makedirs(os.path.dirname(path), exist_ok=True)

    content = yaml.dump(output, default_flow_style=False, allow_unicode=True, sort_keys=False)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info(f"Wrote feature_gates.yaml to {path} ({len(gates)} gates)")
    return path


def write_project_config(project_code: str, items: list, output_path: str, fmt: str = "yaml") -> str:
    """Write project config file from DB items."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    if fmt == "yaml":
        data = {}
        for item in items:
            # Try JSON parse for structured values
            try:
                parsed = json.loads(item.value)
            except (json.JSONDecodeError, TypeError):
                parsed = item.value
            data[item.key] = parsed

        content = yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"# Generated by OpsCenter\n")
            f.write(content)

    elif fmt == "env":
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"# Generated by OpsCenter\n")
            for item in items:
                f.write(f"{item.key}={item.value}\n")

    elif fmt == "json":
        data = {}
        for item in items:
            try:
                parsed = json.loads(item.value)
            except (json.JSONDecodeError, TypeError):
                parsed = item.value
            data[item.key] = parsed
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    logger.info(f"Wrote {project_code} config to {output_path} ({len(items)} items)")
    return output_path


def write_platforms_yaml(items: list) -> str:
    """Generate platforms.yaml from DB platform_credential items."""
    import yaml
    platforms = {}
    for item in items:
        try:
            data = json.loads(item.value)
        except (json.JSONDecodeError, TypeError):
            data = {"credentials": item.value}
        platforms[item.key] = {
            "enabled": data.get("enabled", True),
            "credentials": data.get("credentials", {}),
        }

    path = os.path.join(settings.config_output_dir, "multi-publish", "platforms.yaml")
    os.makedirs(os.path.dirname(path), exist_ok=True)

    output = {
        "version": "1",
        "_generated_by": "ops-center",
        "_generated_at": __import__("datetime").datetime.utcnow().isoformat(),
        "platforms": platforms,
    }
    content = yaml.dump(output, default_flow_style=False, allow_unicode=True, sort_keys=False)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"Wrote platforms.yaml to {path} ({len(platforms)} platforms)")
    return path


def write_project_params(project_code: str, items: list, output_path: str) -> str:
    """Generate project parameter config file."""
    import yaml
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    params = {}
    for item in items:
        try:
            params[item.key] = json.loads(item.value)
        except (json.JSONDecodeError, TypeError):
            # Convert to typed value
            v = item.value
            if item.value_type == "number":
                v = float(v) if "." in v else int(v)
            elif item.value_type == "boolean":
                v = v.lower() in ("true", "1", "yes")
            params[item.key] = v

    output = {
        "_generated_by": "ops-center",
        "_generated_at": __import__("datetime").datetime.utcnow().isoformat(),
        "params": params,
    }
    content = yaml.dump(output, default_flow_style=False, allow_unicode=True, sort_keys=False)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by OpsCenter\n")
        f.write(content)
    logger.info(f"Wrote {project_code} params to {output_path} ({len(params)} items)")
    return output_path
