"""Generate config files from DB for each project."""
import os
import logging
import yaml
import json
from pathlib import Path

from config import settings

logger = logging.getLogger(__name__)


def write_feature_gates(items: list) -> str:
    """Write feature_gates.yaml from DB items. Returns the file path."""
    gates = {}
    for item in items:
        gates[item.key] = {
            "enabled": item.value.lower() in ("true", "1", "yes"),
            "tier": 1,  # Default; can be overridden by a separate config item
            "description": item.description,
        }

    # Load tier info from config items if present
    # (tier info stored as separate config items like "feature_flag_tier.xxx")

    output = {}
    output["version"] = "1"
    output["gates"] = gates
    output["_generated_by"] = "ops-center"
    output["_generated_at"] = __import__("datetime").datetime.utcnow().isoformat()

    path = settings.orchestrator_feature_gates_path
    os.makedirs(os.path.dirname(path), exist_ok=True)

    content = yaml.dump(output, default_flow_style=False, allow_unicode=True, sort_keys=False)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info(f"Wrote feature_gates.yaml to {path} ({len(gates)} gates)")
    return path


def write_project_config(project_code: str, items: list, output_path: str, fmt: str = "yaml") -> str:
    """Write project config file from DB items."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    if fmt == "yaml":
        data = {}
        for item in items:
            # Try JSON parse for structured values
            try:
                parsed = json.loads(item.value)
            except (json.JSONDecodeError, TypeError):
                parsed = item.value
            data[item.key] = parsed

        content = yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"# Generated by OpsCenter\n")
            f.write(content)

    elif fmt == "env":
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"# Generated by OpsCenter\n")
            for item in items:
                f.write(f"{item.key}={item.value}\n")

    elif fmt == "json":
        data = {}
        for item in items:
            try:
                parsed = json.loads(item.value)
            except (json.JSONDecodeError, TypeError):
                parsed = item.value
            data[item.key] = parsed
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    logger.info(f"Wrote {project_code} config to {output_path} ({len(items)} items)")
    return output_path
